### ISSUE TITLE
negative info doesn't show camera info

### ISSUE THREAD

**Issue by djjudas21** [djjudas21/photodb-perl#199]
Command `negative info` doesn't show camera info:

```yaml
---
- Aperture: f/8.0
  Caption: Hannah & Edmund at Hannah & Darren's wedding
  Date: 2014-08-10 00:00:00
  Exposure program: Aperture-priority AE
  Filename: 220-1-img245.jpg
  Film ID: 220
  Focal length: 50mm
  Frame: 1
  Lens: Canon New FD 50mm f/1.4
  Location: '52.519466, -1.509889'
  Metering mode: Center-weighted average
  Negative ID: 4929
  Photographer: Jonathan Gazeley
  Prints made: 0
  Shutter speed: 1/60
```
